name: Daily Facilitator Picker

on:
  # At ~9:00 am on weekdays. UTC => 7:00
  # https://crontab.guru/#0_10_*_*_MON-FRI
  schedule:
    - cron: "0 7 * * MON-FRI"
  workflow_dispatch: # allows manual rerunning in github actions

jobs:
  notify: # facilitator of the daily tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # allows accessing files from the repo
      - name: Pick Today's Facilitator
        run: ./.github/scripts/randomMemberPicker.sh
        id: facilitator
    
      - name: Notify my test BKK teams channel
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.BKK_PIP_TEST_CHANNEL }}
          summary: alert the team who is the facilitator today
          title: ${{ steps.facilitator.outputs.FACILITATOR }} is the daily facilitator today.
          text: " @Pip You can prepare with [our daily script](https://climatepartner.atlassian.net/wiki/spaces/TB/pages/1042677793/Dailies) "
          
          

    # admin-frontend has the most advanced git hub actions pipeline :)
    # watch/read some github actions info !

  #https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

  # https://developer.personio.de/docs/getting-started-with-the-personio-api also gonna be useful
